server:
  #当前eureka的服务端口
  port: 8761
eureka:
  client:
    #是否将eureka Server 服务作为客户端进行注册
    allow-redirects: false
    #是否获取其他 eureka Server 服务的数据
    fetch-registry: true
    #注册中心的访问地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
